spring:
  application:
    name: smart-campus-backend
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://dbUser:mandi2002@ac-uzjg786-shard-00-00.hevkrki.mongodb.net:27017,ac-uzjg786-shard-00-01.hevkrki.mongodb.net:27017,ac-uzjg786-shard-00-02.hevkrki.mongodb.net:27017/smartcampus_db?ssl=true&replicaSet=atlas-moih8k-shard-0&authSource=admin&appName=Cluster0}
      auto-index-creation: true
  mongo:
    auto-index-creation: true

google:
  auth:
    client-id: ${GOOGLE_AUTH_CLIENT_ID:384649476958-c6b17p693e4kt4spnovf3qnm8danqlt0.apps.googleusercontent.com}

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:Admin@1234}
  display-name: ${ADMIN_DISPLAY_NAME:Administrator}
  email: ${ADMIN_EMAIL:admin@smartcampus.local}

server:
  port: ${PORT:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  port: ${PORT:8080}
